language: perl
perl:
    - "5.22"
    # - "5.20"
    # - "5.18"
    # - "5.16"
    # - "5.14"
    # - "5.12"
    # - "5.10"

dist: trusty
# sudo: require # ubuntu
sudo: required

# services:
#   - docker
services:
  - mysql

addons:
  apt:
    packages:
    # - mysql-server-core-5.5
    # - mysql-server-5.5
    # - mysql-client-core-5.5
    # - mysql-client-5.5
    # - mysql-server-core-5.6
    # - mysql-server-5.6
    # - mysql-client-core-5.6
    # - mysql-client-5.6
    - ocaml 
    - libbtparse-dev # disallowed in travis # Text::BibTeX  requires it
    - libdbd-mysql-perl
    - tree # just for debugging dir structure

git:
  depth: 3

before_install:
    - sudo apt-get install -y texlive-base bibtex2html 
    # - bash install-bibtex2html.sh
    # - git config --global user.name "TravisCI"
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - pwd
    - tree
    - export AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j1:c HARNESS_TIMER=1


# install:
#     - cpanm -nq --no-interactive --installdeps .

before_script:
    - mysql --version
    - mysql -u root -e "SELECT VERSION();"
    - mysql -u root -e 'create database IF NOT EXISTS bibspace;'
    - mysql -u root -e "CREATE USER 'bibspace_user'@'localhost' IDENTIFIED BY 'passw00rd';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON bibspace.* TO 'bibspace_user'@'localhost';"
    - mysql -u root -e "FLUSH PRIVILEGES;"
    - mojo version
    - coverage-setup


notifications:
    email:
        on_success: always
        on_failure: always

script: 
    - export BIBSPACE_CONFIG=lib/BibSpace/files/config/default.conf
    - export BIBSPACE_USE_DUMP=1
    - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lr t/

after_success:
    - cover -report coveralls

after_failure:
    - tree
    - tail -n 1000 log/error.log
    - tail -n 1000 log/warn.log
    - tail -n 1000 log/development.log

