language: perl
perl:
    # - "blead"
    # - "5.22"
    - "5.20"
    # - "5.18"
    # - "5.16"
    # - "5.14"
    # - "5.12"
    # - "5.10"

dist: trusty
sudo: true
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y tree
    - sudo apt-get install -y ocaml libbtparse-dev libdbd-mysql-perl
    - bash install-bibtex2html.sh
    - eval $(curl https://travis-perl.github.io/init) --auto


install:
    - export AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j1:c HARNESS_TIMER=1
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls
    - cpanm -n --verbose --no-interactive --installdeps --with-develop --with-recommends --with-suggests .
    # - perl Build.PL 
    # - ./Build
    # - ./Build install
    # - cpanm  Mojolicious DBD::mysql Module::Build::Mojolicious Time::Piece Data::Dumper 
    # - cpanm --quiet --notest Crypt::Eksblowfish::Bcrypt Cwd File::Find DateTime File::Copy  Scalar::Util 
    # - cpanm --quiet --notest utf8 File::Slurp DBI Exporter Set::Scalar Session::Token LWP::UserAgent 
    # - cpanm --quiet --notest Text::BibTeX HTML::TagCloud::Sortable Crypt::Random 
    # - cpanm --quiet --notest Test::Differences Test::MockModule WWW::Mailgun Mojolicious::Plugin::RenderFile Path::Tiny
    # - cpanm --quiet --notest --installdeps .

before_script:
    - mysql --version
    - mysql -u root -e "SELECT VERSION();"
    - mysql -u root -e 'create database IF NOT EXISTS bibspacetest;'
    - tree . 
    - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
    # - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root


notifications:
    email: true

script: 
    - BIBSPACE_CONFIG=config/testing.conf PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t/
    - perl Build.PL && BIBSPACE_CONFIG=config/testing.conf  ./Build build && cover -test -report coveralls
    - cover


after_success:
    - cover -report coveralls

