language: perl
perl:
    # - "blead"
    # - "5.22"
    - "5.20"
    # - "5.18"
    # - "5.16"
    # - "5.14"
    # - "5.12"
    # - "5.10"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ocaml libbtparse-dev libdbd-mysql-perl
  - bash install-bibtex2html.sh

install:
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j1:c HARNESS_TIMER=1
    - cpanm --quiet --notest Mojolicious DBD::mysql Module::Build::Mojolicious Time::Piece Data::Dumper Crypt::Eksblowfish::Bcrypt Cwd File::Find DateTime File::Copy  Scalar::Util utf8 File::Slurp DBI Exporter Set::Scalar Session::Token LWP::UserAgent Net::Address::IP::Local Text::BibTeX HTML::TagCloud::Sortable Crypt::Random Test::Differences Test::MockModule WWW::Mailgun
    # - cpanm --quiet --notest --installdeps .

sudo: true

notifications:
    email: true

version: 1.4.2
=======
#    - "blead"
#    - "5.22"
    - "5.20"
#    - "5.18"
#    - "5.16"
#    - "5.14"
#    - "5.12"
    - "5.10"


install:
    - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j1:c HARNESS_TIMER=1
    - cpanm --quiet --notest Mojolicious Time::Piece Data::Dumper Crypt::Eksblowfish::Bcrypt Cwd File::Find DateTime File::Copy  Scalar::Util utf8 File::Slurp DBI Exporter Set::Scalar Session::Token LWP::UserAgent Net::Address::IP::Local Text::BibTeX HTML::TagCloud::Sortable Crypt::Random Test::Differences Test::MockModule WWW::Mailgun
#    - cpanm --quiet --notest --installdeps .

sudo: false

notifications:
    email: false
